services:
  # 1. The Backend (API)
  - type: web
    name: findash-api-manish
    env: node
    plan: free
    rootDir: server
    # We add 'ls' to debug if paths are correct
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npm run db:setup
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: "file:./dev.db"

  # 2. The Frontend (UI)
  - type: web
    name: findash-ui-manish
    env: static
    rootDir: client
    buildCommand: npm install && chmod +x node_modules/.bin/* && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://findash-api-manish.onrender.com